### ISSUE TITLE
Videos not playing on iOS

### ISSUE THREAD

**Issue by thetwopct** [souravm84/vidbacking#1]
Hey! Great script, very simple to use. I can't get videos playing on my latest iOS (including your demos) just wondered if this was a known issue or what 👍

**Comment by souravm84** [comment]
Thank for this info. Which browser you tested? Please share the browser console log and screenshots. Hopefully we can solve it.

**Comment by thetwopct** [comment]
Latest Safari with latest iOS. I don't have it installed at the moment on the site I am working on, so not sure I can help much more right now

**Comment by souravm84** [comment]
Sorry for this late reply. I research this issue in details and found it -  This is all about user's settings on their phone. If data saving mode is active, no background video will play.
