### ISSUE TITLE
Console error when video is completely out of viewport

### ISSUE THREAD

**Issue by wernergusset** [souravm84/vidbacking#2]
In your demo youtube video in a div: when the video div is completely out of viewport at scrolling there is this error in the console

TypeError: obj[0].pause is not a function
    at jquery.vidbacking.js:258

Do you no how to fix this?

I am trying to use the script on a site where I discovered the problem and found it in your demo too?

**Comment by souravm84** [comment]
Thank you for reporting this issue. I will check and get back to you as soon as possible.

**Comment by MordiSacks** [comment]
got same issue

**Comment by souravm84** [comment]
Issue fixed. in version 2.1.0

**Comment by tayloredu** [comment]
I'm also facing this issue on my website ([https://capcutpromodapk.net/healing-thailand-capcut-template/](https://capcutpromodapk.net/healing-thailand-capcut-template)) please guide me on how to fix this issue.

**Comment by souravm84** [comment]
> I'm also facing this issue on my website ([https://capcutpromodapk.net/healing-thailand-capcut-template/](https://capcutpromodapk.net/healing-thailand-capcut-template)) please guide me on how to fix this issue.

have not found the use of vidbacking on the page link you shared. Please give the correct page link, so I can check the issue.

**Comment by Earnner** [comment]
I'm also facing this issue on my website ([https://battleofgym.com/bodybuilder-shares-4-key-tips-to-get-better-gains-in-the-gym/) please guide me on how to fix this issue.

**Comment by Earnner** [comment]
I'm also facing this issue on my website   (##[https://battleofgym.com/5-effective-ways-to-reduce-arm-fat-join-fitness-fit/])
(please guide me on how to fix this issue.

**Comment by Earnner** [comment]
I'm also facing this issue on my website
[https://battleofgym.com/5-effective-ways-to-reduce-arm-fat-join-fitness-fit/](url)
please guide me on how to fix this issue.
