### ISSUE TITLE
Demo Example does not work for me

### ISSUE THREAD

**Issue by Niclas1337** [souravm84/vidbacking#3]
Somehow, the demo example and any other try using your JS failed while playing a video from yt in the background.

I only get a grey screen from youtube with the message: "video not available".

any idea why?

**Comment by souravm84** [comment]
As you are getting the message "video not available". It means either that video is not available at youtube, or that youtube video is restricted in your area. It has nothing todo with the plugin. I tested and found all demos are working fine.
